package com.bdqn.mapper;

import com.bdqn.bean.Country;

public interface CountryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table country
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table country
	 * @mbg.generated
	 */
	int insert(Country record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table country
	 * @mbg.generated
	 */
	int insertSelective(Country record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table country
	 * @mbg.generated
	 */
	Country selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table country
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Country record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table country
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Country record);
}