package com.bdqn.mapper;

import com.bdqn.bean.Player;

public interface PlayerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table player
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer playerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table player
	 * @mbg.generated
	 */
	int insert(Player record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table player
	 * @mbg.generated
	 */
	int insertSelective(Player record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table player
	 * @mbg.generated
	 */
	Player selectByPrimaryKey(Integer playerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table player
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Player record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table player
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Player record);
}