package com.bdqn.mapper;

import com.bdqn.bean.SysPrivilege;

public interface SysPrivilegeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_privilege
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_privilege
	 * @mbg.generated
	 */
	int insert(SysPrivilege record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_privilege
	 * @mbg.generated
	 */
	int insertSelective(SysPrivilege record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_privilege
	 * @mbg.generated
	 */
	SysPrivilege selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_privilege
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(SysPrivilege record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_privilege
	 * @mbg.generated
	 */
	int updateByPrimaryKey(SysPrivilege record);
}