package com.bdqn.mapper;

import com.bdqn.bean.SysRolePrivilege;

public interface SysRolePrivilegeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_privilege
	 * @mbg.generated
	 */
	int insert(SysRolePrivilege record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role_privilege
	 * @mbg.generated
	 */
	int insertSelective(SysRolePrivilege record);
}