package com.bdqn.mapper;

import com.bdqn.bean.SysUserRole;

public interface SysUserRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbg.generated
	 */
	int insert(SysUserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbg.generated
	 */
	int insertSelective(SysUserRole record);
}