package com.bdqn.mapper;

import java.util.List;

import com.bdqn.bean.Team;

public interface TeamMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table team
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer teamId);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table team
	 * @mbg.generated
	 */
	int insert(Team record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table team
	 * @mbg.generated
	 */
	int insertSelective(Team record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table team
	 * @mbg.generated
	 */
	Team selectByPrimaryKey(Integer teamId);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table team
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Team record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table team
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Team record);


	int insertTeam(Team team);
	
	
	List<Team> selectByIds(List<Integer> ids);
	
	List<Team> selectByTeam(Team team);
	
	int update(Team t);
	
}