package com.bdqn.mapper;

import com.bdqn.bean.TStudent;

public interface TStudentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_student
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer studentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_student
	 * @mbg.generated
	 */
	int insert(TStudent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_student
	 * @mbg.generated
	 */
	int insertSelective(TStudent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_student
	 * @mbg.generated
	 */
	TStudent selectByPrimaryKey(Integer studentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_student
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TStudent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_student
	 * @mbg.generated
	 */
	int updateByPrimaryKey(TStudent record);
}