package com.bdqn.bean;

import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table team
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Team {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column team.team_id
	 * @mbg.generated
	 */
	private Integer teamId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column team.team_name
	 * @mbg.generated
	 */
	private String teamName;

	private List<Player> players;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column team.team_id
	 * @return  the value of team.team_id
	 * @mbg.generated
	 */
	public Integer getTeamId() {
		return teamId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column team.team_id
	 * @param teamId  the value for team.team_id
	 * @mbg.generated
	 */
	public void setTeamId(Integer teamId) {
		this.teamId = teamId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column team.team_name
	 * @return  the value of team.team_name
	 * @mbg.generated
	 */
	public String getTeamName() {
		return teamName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column team.team_name
	 * @param teamName  the value for team.team_name
	 * @mbg.generated
	 */
	public void setTeamName(String teamName) {
		this.teamName = teamName == null ? null : teamName.trim();
	}

 

	 

	public List<Player> getPlayers() {
		return players;
	}

	public void setPlayers(List<Player> players) {
		this.players = players;
	}

	@Override
	public String toString() {
		return "Team [teamId=" + teamId + ", teamName=" + teamName + ", players=" + players + "]";
	}

 
	
	
	

	
}