package com.bdqn.bean;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_student
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TStudent {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_student.student_id
	 * @mbg.generated
	 */
	private Integer studentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_student.student_name
	 * @mbg.generated
	 */
	private String studentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_student.student_phone
	 * @mbg.generated
	 */
	private String studentPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_student.student_gender
	 * @mbg.generated
	 */
	private Integer studentGender;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_student.student_id
	 * @return  the value of t_student.student_id
	 * @mbg.generated
	 */
	public Integer getStudentId() {
		return studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_student.student_id
	 * @param studentId  the value for t_student.student_id
	 * @mbg.generated
	 */
	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_student.student_name
	 * @return  the value of t_student.student_name
	 * @mbg.generated
	 */
	public String getStudentName() {
		return studentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_student.student_name
	 * @param studentName  the value for t_student.student_name
	 * @mbg.generated
	 */
	public void setStudentName(String studentName) {
		this.studentName = studentName == null ? null : studentName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_student.student_phone
	 * @return  the value of t_student.student_phone
	 * @mbg.generated
	 */
	public String getStudentPhone() {
		return studentPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_student.student_phone
	 * @param studentPhone  the value for t_student.student_phone
	 * @mbg.generated
	 */
	public void setStudentPhone(String studentPhone) {
		this.studentPhone = studentPhone == null ? null : studentPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_student.student_gender
	 * @return  the value of t_student.student_gender
	 * @mbg.generated
	 */
	public Integer getStudentGender() {
		return studentGender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_student.student_gender
	 * @param studentGender  the value for t_student.student_gender
	 * @mbg.generated
	 */
	public void setStudentGender(Integer studentGender) {
		this.studentGender = studentGender;
	}
}